version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - n 20

  pre_build:
    commands:
      - npm ci

  build:
    commands:
      - PRIORITY=$(shuf -i 1-50000 -n 1)
