version: 0.2

env:
  parameter-store:
    DB_HOST: TemporaryDatabaseHost

phases:
  install:
    runtime-versions:
      nodejs: 18.x
    commands:
      - echo "Installing dependencies..."

  pre_build:
    commands:

  build:
    commands:
